server:
  port: ${SERVER_PORT:0}

triplestore:
  database:
    dir: ${TRIPLESTORE_DB_PATH:/tmp/tdb2}

spring:
  config:
    import:
      - classpath:config/security.yml
      - classpath:config/artemis.yml
